#-- v3 syntax
version: '3'

services:
 #POSTGRES 10.1 
 postgres:
   image: postgres:10.1
   restart: always
   environment:
     - POSTGRES_DB=app
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=admin
   volumes:
     - ./db-data/:/var/lib/postgresql/data
   ports:
     - 5432:5432

 #APACHE PHP 7.2
 apachephp72:
    build: .
    container_name: itego-dev-apache
    restart: always
    environment:
      TIMEZONE: "America/Sao_Paulo"
      PHP_MEMORY_LIMIT: "512M"
      MAX_UPLOAD: "50M"
      PHP_MAX_FILE_UPLOAD: "200"
      PHP_MAX_POST: "100M"
      XDEBUG_ENABLED: "true"
      XDEBUG_CONFIG: "remote_enable=1 remote_autostart = 1 remote_connect_back = 1" 
      PHP_IDE_CONFIG: "serverName=php-docker.local"
    volumes:
      - ./public:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "80:80"
    depends_on:
      - postgres
    links:
      - postgres

 #PGADMIN 4
 pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com" 
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "8080:80"
    depends_on:
      - postgres
    links:
      - postgres
