#-- v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  hibrida-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: hibrida-mysql
    volumes:
      - ./.db-data/:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=hibrida    
      - MYSQL_DATABASE=hibrida
      - MYSQL_USER=hibrida
      - MYSQL_PASSWORD=hibrida

  # PHP (with Nginx)
  app:
    image: 1and1internet/ubuntu-16-apache-php-5.6
    container_name: hibrida-apache
    environment:
      XDEBUG_ENABLED: "true"
      XDEBUG_CONFIG: "remote_host=192.168.25.3"
      PHP_IDE_CONFIG: "serverName=dev.local"
    volumes:
      - ./public:/var/www
      - ./config/vhost.conf:/etc/apache2/sites-available/vhost.conf
      - ./config/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
      #- ./config/php.ini:/usr/local/etc/php/php.ini
      #- ./config/www.conf:/etc/php7/php-fpm.d/www.conf
      
    ports:
      - "80:80"
    links:
      - mysql
