#-- v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  portal-dev-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: portal-dev-mysql
    volumes:
      - ./db-data/:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=portal
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin

  apachephp:
    build: .
    container_name: portal-dev-apache
    environment:
      TIMEZONE: "America/Sao_Paulo"
      PHP_MEMORY_LIMIT: "512M"
      MAX_UPLOAD: "50M"
      PHP_MAX_FILE_UPLOAD: "200"
      PHP_MAX_POST: "100M"
      XDEBUG_ENABLED: "true"
      XDEBUG_CONFIG: "remote_enable=1 remote_autostart = 1 remote_connect_back = 1 var_display_max_children=-1 var_display_max_data=-1 var_display_max_depth=-1"
      PHP_IDE_CONFIG: "serverName=php-docker.local"
    volumes:
      - ./public:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "80:80"
    depends_on:
      - mysql
    links:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
    depends_on:
      - mysql
    links:
      - mysql
