#-- v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  phpdev-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: phpdev-mysql
    volumes:
      - ./db-data/:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=phpdev    
      - MYSQL_DATABASE=phpdev
      - MYSQL_USER=phpdev
      - MYSQL_PASSWORD=phpdev

  # PHP (with Nginx)
  app:
    image: ambientum/php:7.1-nginx
    container_name: phpdev-nginx
    environment:
      TIMEZONE: "America/Sao_Paulo"
      PHP_MEMORY_LIMIT: "512M"
      MAX_UPLOAD: "50M"
      PHP_MAX_FILE_UPLOAD: "200"
      PHP_MAX_POST: "100M"
      XDEBUG_ENABLED: "true"
      XDEBUG_CONFIG: "remote_enable=1 remote_autostart = 1 remote_connect_back = 1"
      PHP_IDE_CONFIG: "serverName=php-docker.local"
    volumes:
      - ./public:/var/www/app/public
      - ./config/php.ini:/etc/php7/php.ini
      - ./config/www.conf:/etc/php7/php-fpm.d/www.conf
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx-error.log/error.log:/var/log/nginx/error.log;
      - ./logs/mysql-error.log:/var/log/mysql/error.log;
    ports:
      - "80:8080"
    depends_on:
      - mysql
    links:
      - mysql

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
    depends_on:
      - mysql
    links:
      - mysql
